### ISSUE TITLE
DKB-Integration

### ISSUE THREAD

**Issue by confluencepoint** [bahlo/ing-ynab#109]
Unter [Ing-ynab: Automatischer Importer für ING (Deutschland)](https://www.didyc.de/t/ing-ynab-automatischer-importer-fuer-ing-deutschland/817/2) hatte sich ein Anwender mit Interesse an der **DKB**-Integration gemeldet. 

_Kam die Lauffähigkeit zustande?_

**Comment by bahlo** [comment]
Hi. Nein, habe bisher keine Email bekommen. Wenn du Interesse hast können wir uns das mal anschauen.

**Comment by confluencepoint** [comment]
Ich habe Dir eine E-Mail geschrieben.
