### ISSUE TITLE
Improve FinTS registration docs

### ISSUE THREAD

**Issue by behren** [bahlo/ing-ynab#95]
Hey Arne, I would love to use this, but honestly I have no idea how to register my "FinTS product". 
I have trouble identifying what information is needed in order to register the product (what "product" are we even talking about here?).

Would `Firmenbezeichnung` be your name and `Produktname` be `ing-ynab`? Maybe we can improve the README? I feel pretty dumb and lost here...

Thanks!

**Comment by bahlo** [comment]
Hi @behren, I would set your name as `Firmenbezeichnung` and `ing-ynab` as `Produktbezeichnung`. I don't think it matters that much tbh.

That being said, I agree the README could be more helpful. Let me know if you run into any other issues setting this up!
